### ISSUE TITLE
From integration? 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ryo33/enum_downcast#5]
anyhow support automatic downcast on several layers if From implemented

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dd4dae5afb75df2c5f212bdf423f9d7d

**Comment by ryo33** [comment]
Could you provide more detailed context that you expect to utilize the From trait? Generally, using `enum_downcast` with such crates like `derive_more` which provides a `From` derive macro should work as expected.
